disabled_rules:
  - trailing_whitespace
  - identifier_name
  - line_length

opt_in_rules:
  - empty_count
  - explicit_init
  - fatal_error_message

line_length:
  warning: 140
  error: 200
  ignores_comments: true
  ignores_interpolated_strings: true

excluded:
  - build
  - .build
  - node_modules
  - ios/App/public

reporter: "xcode"
